On this weekend, we are going to learn various data visualizations techniques that we can use to understand and analyse our data, as well as draw important insights.

* Don't worry about the syntax of these commands. You can always refer to this notebook in the future for reference.

* Focus on the different types of visualizations possible.

* Think about how you could use these visualizations in non-trivial ways.

In [ ]:
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go
import plotly.figure_factory as ff
from plotly.subplots import make_subplots

In [ ]:
df_stocks = pd.read_csv("stock_price_data_with_date.csv")

In [ ]:
df_stocks

         Date  adaniports  asianpaints  axisbank   cipla      tcs
0    01/01/08     1296.85      1123.19    972.55  211.10  1054.55
1    02/01/08     1307.45      1135.45   1034.65  218.85  1050.00
2    03/01/08     1275.80      1133.90   1035.85  216.35  1011.05
3    04/01/08     1240.35      1150.08   1054.90  213.65  1005.20
4    07/01/08     1227.25      1182.62   1090.15  212.65   975.60
..        ...         ...          ...       ...     ...      ...
241  24/12/08      312.80       868.23    490.75  181.05   478.15
242  26/12/08      305.45       868.44    482.80  181.95   471.65
243  29/12/08      315.75       867.77    494.95  184.00   476.80
244  30/12/08      319.70       873.45    510.25  183.90   482.55
245  31/12/08      325.30       883.53    504.70  186.60   477.90

[246 rows x 6 columns]

# Visualising the Data using Box Plot

In [ ]:
fig = px.box(df_stocks, x="asianpaints",points="all")
fig.show()

## Plot all the stocks together

In [ ]:
fig = go.Figure()

for col in df_stocks:
  if col != "Date":
    fig.add_trace(go.Box(y=df_stocks[col].values, name=df_stocks[col].name, boxpoints = 'all'))

fig.show()

Without using for-loop

In [ ]:
df_stocks_melt = pd.melt(df_stocks.drop("Date",axis=1))

In [ ]:
df_stocks_melt

        variable    value
0     adaniports  1296.85
1     adaniports  1307.45
2     adaniports  1275.80
3     adaniports  1240.35
4     adaniports  1227.25
...          ...      ...
1225         tcs   478.15
1226         tcs   471.65
1227         tcs   476.80
1228         tcs   482.55
1229         tcs   477.90

[1230 rows x 2 columns]

In [ ]:
df_stocks_melt = pd.melt(df_stocks.drop("Date",axis=1))
fig = px.box(df_stocks_melt, x="variable",y="value",points="all",color="variable")
fig.show()

## **DIY:**

Convert these numbers to z-score (in a new DataFrame) and redo the box plot

In [ ]:
# Extract the stock prices of TCS from df_stocks as a list. Call it tcs_price_list

tcs_price_list = list(df_stocks["tcs"])

In [ ]:
df_stats = df_stocks.describe()

In [ ]:
df_stats

        adaniports  asianpaints     axisbank       cipla          tcs
count   246.000000   246.000000   246.000000  246.000000   246.000000
mean    592.167073  1118.204106   752.574187  207.112398   789.026016
std     215.631456   123.289063   188.337102   17.688713   163.968174
min     257.950000   850.850000   376.550000  160.100000   453.850000
25%     436.987500  1032.242500   634.700000  194.175000   679.250000
50%     580.150000  1157.655000   721.525000  208.575000   844.450000
75%     731.262500  1215.397500   875.337500  218.887500   898.400000
max    1307.450000  1286.430000  1268.150000  240.700000  1054.550000

In [ ]:
# Compute the mean and standard deviation of the values in this list

tcs_mean = df_stats.loc["mean"]["tcs"]
tcs_std = df_stats.loc["std"]["tcs"]

print("Mean of TCS : ", tcs_mean)
print("STD of TCS : ",tcs_std)

Mean of TCS :  789.0260162601625
STD of TCS :  163.9681744069585

In [ ]:
# Compute Mean and STD without using DataFrame through NumPy

tcs_mean = np.mean(np.array(tcs_price_list))
tcs_std = np.std(np.array(tcs_price_list))

print("Mean of TCS : ", tcs_mean)
print("STD of TCS : ",tcs_std)

Mean of TCS :  789.0260162601625
STD of TCS :  163.63456638199685

In [ ]:
# Create a new empty DataFrame. Call it df_stocks_zscore

df_stocks_zscore = pd.DataFrame()

# Create another list with the z-score values

tcs_price_list = list(df_stocks["tcs"])

tcs_mean = np.mean(np.array(tcs_price_list))
tcs_std = np.std(np.array(tcs_price_list))

tcs_zscore_list = []

for price in tcs_price_list:
  zscore = (price-tcs_mean)/tcs_std
  tcs_zscore_list.append(zscore)

# Append this new z-score value list to the new DataFrame created

df_stocks_zscore["tcs"] = tcs_zscore_list

In [ ]:
df_stocks_zscore

          tcs
0    1.622664
1    1.594859
2    1.356828
3    1.321078
4    1.140187
..        ...
241 -1.899819
242 -1.939541
243 -1.908069
244 -1.872930
245 -1.901347

[246 rows x 1 columns]

In [ ]:
df_stocks_zscore.describe()

                tcs
count  2.460000e+02
mean   8.665155e-16
std    1.002039e+00
min   -2.048320e+00
25%   -6.708608e-01
50%    3.387058e-01
75%    6.684039e-01
max    1.622664e+00

In [ ]:
fig = px.box(df_stocks_zscore, x="tcs",points="all")
fig.show()

In [ ]:
# Write a for-loop to do this for all the stocks

# Create a new empty DataFrame. Call it df_stocks_zscore

df_stocks_zscore = pd.DataFrame()

# This for-loop iterates over every column of the df_stocks dataframe
# This outer loop runs for each column in the df_stocks dataframe, but bypass the Date column
for col in df_stocks:

  if col != "Date":
    # extracts the values for the particular column and saves it as a list called price_list
    price_list = list(df_stocks[col])
    print('Column Name : ',col)

    # Find the mean and standard deviation for the price list using NumPy
    mean = np.mean(np.array(price_list))
    std = np.std(np.array(price_list))

    # Initialise an empty zscore_list in each iteration to store the z-score values for that particular stock
    zscore_list = []

    # Iterate over the original prices of the stock, compute the z-score values and append it to the zscore_list
    # This inner loop runs over each row of the dataframe (i.e. each value in price_list for the selected column)
    for price in price_list:
      zscore = (price-mean)/std
      zscore_list.append(zscore)

    # Append this new z-score value list to the new DataFrame created
    df_stocks_zscore[col] = zscore_list

Column Name :  adaniports
Column Name :  asianpaints
Column Name :  axisbank
Column Name :  cipla
Column Name :  tcs

In [ ]:
df_stocks

         Date  adaniports  asianpaints  axisbank   cipla      tcs
0    01/01/08     1296.85      1123.19    972.55  211.10  1054.55
1    02/01/08     1307.45      1135.45   1034.65  218.85  1050.00
2    03/01/08     1275.80      1133.90   1035.85  216.35  1011.05
3    04/01/08     1240.35      1150.08   1054.90  213.65  1005.20
4    07/01/08     1227.25      1182.62   1090.15  212.65   975.60
..        ...         ...          ...       ...     ...      ...
241  24/12/08      312.80       868.23    490.75  181.05   478.15
242  26/12/08      305.45       868.44    482.80  181.95   471.65
243  29/12/08      315.75       867.77    494.95  184.00   476.80
244  30/12/08      319.70       873.45    510.25  183.90   482.55
245  31/12/08      325.30       883.53    504.70  186.60   477.90

[246 rows x 6 columns]

In [ ]:
df_stocks_zscore

     adaniports  asianpaints  axisbank     cipla       tcs
0      3.274659     0.040523  1.170371  0.225892  1.622664
1      3.323918     0.140167  1.500771  0.664917  1.594859
2      3.176840     0.127569  1.507156  0.523296  1.356828
3      3.012104     0.259073  1.608510  0.370345  1.321078
4      2.951228     0.523544  1.796056  0.313697  1.140187
..          ...          ...       ...       ...       ...
241   -1.298218    -2.031678 -1.393023 -1.476395 -1.899819
242   -1.332373    -2.029972 -1.435321 -1.425412 -1.939541
243   -1.284509    -2.035417 -1.370677 -1.309282 -1.908069
244   -1.266154    -1.989253 -1.289274 -1.314947 -1.872930
245   -1.240131    -1.907327 -1.318803 -1.161996 -1.901347

[246 rows x 5 columns]

In [ ]:
# Plot the Box Plot for the z-score values of all the 5 stocks using for-loop

fig = go.Figure()

for col in df_stocks_zscore:
  if col != "Date":
    fig.add_trace(go.Box(y=df_stocks_zscore[col].values, name=df_stocks_zscore[col].name, boxpoints = 'all'))

fig.show()

In [ ]:
# Plot the Box Plot for the z-score values of all the 5 stocks WITHOUT using for-loop

df_stocks_zscore_melt = pd.melt(df_stocks_zscore)
fig = px.box(df_stocks_zscore_melt, x="variable",y="value",points="all",color="variable")
fig.show()

In [ ]:
df_stocks_zscore_melt

        variable     value
0     adaniports  3.274659
1     adaniports  3.323918
2     adaniports  3.176840
3     adaniports  3.012104
4     adaniports  2.951228
...          ...       ...
1225         tcs -1.899819
1226         tcs -1.939541
1227         tcs -1.908069
1228         tcs -1.872930
1229         tcs -1.901347

[1230 rows x 2 columns]

# Violin Plot

In [ ]:
fig = px.violin(df_stocks, x="asianpaints",points="all")
fig.show()

In [ ]:
fig = px.violin(df_stocks, x="tcs",points="all")
fig.show()

In [ ]:
fig = px.violin(df_stocks_zscore, x="tcs",points="all")
fig.show()

In [ ]:
fig = px.violin(df_stocks_melt, x="variable",y="value",points="all",color="variable")
fig.show()

In [ ]:
fig = px.violin(df_stocks_melt, y="variable",x="value",points="all",color="variable")
fig.show()

In [ ]:
fig = px.violin(df_stocks_zscore_melt, x="variable",y="value",points="all",color="variable")
fig.show()

# Visualising the Data using Histogram

In [ ]:
fig = px.histogram(df_stocks, x="asianpaints",nbins=50)
fig.show()

In [ ]:
fig = go.Figure()

for col in df_stocks:
  if col != "Date":
    fig.add_trace(go.Histogram(x=df_stocks[col].values, name=df_stocks[col].name))

fig.show()

In [ ]:
# Stack the plots together so that stock values in similar range are on top of each other

fig = go.Figure()

for col in df_stocks:
  if col != "Date":
    fig.add_trace(go.Histogram(x=df_stocks[col].values, name=df_stocks[col].name))

fig.update_layout(barmode='stack')
fig.show()

**DIY:**

Do these histogram plots for the z-score values.

Without using for-loop

In [ ]:
fig = px.histogram(df_stocks_melt, x="value",color="variable")
fig.show()

## Histogram along with Box Plot

In [ ]:
fig = px.histogram(df_stocks_melt, x="value", color="variable",
                   marginal="box", # or violin, rug
                   hover_data=df_stocks_melt.columns, width=1000,height=1000)

fig.show()

# Whats the monthly mean and standard deviation of stock prices?

In [ ]:
df_stocks_monthly_mean = df_stocks.groupby(pd.PeriodIndex(df_stocks['Date'], freq="M")).mean()

# Use "Q" for quarterly average
# Use "W" for weekly average
# Use "Y" for yearly average

In [ ]:
df_stocks_monthly_mean

         adaniports  asianpaints    axisbank       cipla         tcs
Date
2008-01  800.786364  1105.503636  976.729545  200.125000  860.104545
2008-02  714.080000  1135.733000  914.332500  200.427500  878.370000
2008-03  559.636842  1126.688421  764.534211  207.547368  812.297368
2008-04  656.978571  1177.714762  824.190476  214.547619  878.154762
2008-05  741.321429  1199.710000  807.114286  207.807143  907.633333
2008-06  583.569444  1207.361667  732.044444  212.044444  853.791667
2008-07  575.813043  1110.680000  725.897826  216.026087  808.558696
2008-08  597.128571  1180.293810  717.195238  225.819048  819.973810
2008-09  546.875000  1180.659444  729.688889  221.919444  779.222222
2008-10  454.891304  1015.227391  643.221739  192.469565  623.543478
2008-11  446.445000  1027.017000  588.567500  196.150000  656.277500
2008-12  412.700000   975.135500  597.080000  192.677500  599.895000

In [ ]:
# Need to convert the index into a proper timestamp for further processing
df_stocks_monthly_mean.index = df_stocks_monthly_mean.index.to_timestamp()

In [ ]:
df_stocks_monthly_mean

            adaniports  asianpaints    axisbank       cipla         tcs
Date
2008-01-01  800.786364  1105.503636  976.729545  200.125000  860.104545
2008-02-01  714.080000  1135.733000  914.332500  200.427500  878.370000
2008-03-01  559.636842  1126.688421  764.534211  207.547368  812.297368
2008-04-01  656.978571  1177.714762  824.190476  214.547619  878.154762
2008-05-01  741.321429  1199.710000  807.114286  207.807143  907.633333
2008-06-01  583.569444  1207.361667  732.044444  212.044444  853.791667
2008-07-01  575.813043  1110.680000  725.897826  216.026087  808.558696
2008-08-01  597.128571  1180.293810  717.195238  225.819048  819.973810
2008-09-01  546.875000  1180.659444  729.688889  221.919444  779.222222
2008-10-01  454.891304  1015.227391  643.221739  192.469565  623.543478
2008-11-01  446.445000  1027.017000  588.567500  196.150000  656.277500
2008-12-01  412.700000   975.135500  597.080000  192.677500  599.895000

In [ ]:
df_stocks_monthly_std = df_stocks.groupby(pd.PeriodIndex(df_stocks['Date'], freq="M")).std()
df_stocks_monthly_std.index = df_stocks_monthly_std.index.to_timestamp()

In [ ]:
df_stocks_monthly_std

            adaniports  asianpaints    axisbank      cipla         tcs
Date
2008-01-01  237.215986    83.519515  227.699702  17.304959   98.722228
2008-02-01  185.849278    88.393001  164.608242  15.875241   94.428120
2008-03-01  205.051091    86.035136  129.146712  11.957581  120.429482
2008-04-01  188.913623   101.766294  151.413547  14.096342  129.018217
2008-05-01  172.976692    92.226682  126.830298  11.356851  140.659002
2008-06-01  108.623197    84.970072  118.615829   9.006254  113.363380
2008-07-01  173.092338    78.351283  133.268738  12.311182  100.926475
2008-08-01  175.560996    93.320972  126.434406  16.824212  105.623965
2008-09-01  183.119136    43.997285  101.558205   9.380348  103.675000
2008-10-01  174.343413   107.164482  125.054132  16.940489  163.685591
2008-11-01  215.840106   139.763693  219.274197  17.085913  186.706850
2008-12-01  163.392562   160.572348  156.590006  15.420163  174.094029

# Plot the monthly average using bar chart

In [ ]:
fig = px.bar(df_stocks_monthly_mean, x=df_stocks_monthly_mean.index, y="asianpaints",error_y = df_stocks_monthly_std["asianpaints"])
fig.update_layout(title="Monthly average stock price",xaxis_title="Month")
fig.show()

# How to combine bar graphs from multiple stocks?

In [ ]:
fig = px.bar(df_stocks_monthly_mean, x=df_stocks_monthly_mean.index, y=["asianpaints","tcs"],barmode='group')
fig.update_layout(title="Monthly average stock price",xaxis_title="Month")
fig.show()

**DIY:**

Plot the bar plot for all stocks without using for-loop

In [ ]:
fig = go.Figure()

fig.add_trace(
    go.Bar(
      name='Asian Paints',
      x=df_stocks_monthly_mean.index, y=df_stocks_monthly_mean["asianpaints"],
      error_y=dict(type='data',array = np.array(df_stocks_monthly_std["asianpaints"])),marker_color="green"))

fig.add_trace(
    go.Bar(
      name='TCS',
      x=df_stocks_monthly_mean.index, y=df_stocks_monthly_mean["tcs"],
      error_y=dict(type='data',array = np.array(df_stocks_monthly_std["tcs"]))))

fig.update_layout(barmode='group',xaxis_title="Month")
fig.show()

**DIY:**

* Plot the bar graph for all the company stocks along with the std range using for-loop.

* Also try it out for the z-score values, instead of the original stock price.

**DIY:**

Do a bar plot with quarterly data (Use "Q").

In [ ]:
df_stocks_quarterly_mean = df_stocks.groupby(pd.PeriodIndex(df_stocks['Date'], freq="Q")).mean()

In [ ]:
df_stocks_quarterly_mean

        adaniports  asianpaints    axisbank       cipla         tcs
Date
2008Q1  697.245902  1122.013443  890.177869  202.536066  851.202459
2008Q2  664.475833  1194.307167  790.570000  211.437500  881.163333
2008Q3  574.631452  1154.575484  724.050806  221.054032  803.908065
2008Q4  438.815873  1006.242540  611.223016  193.703968  626.427778

In [ ]:
df_stocks_quarterly_mean.index = df_stocks_quarterly_mean.index.to_timestamp()

In [ ]:
df_stocks_quarterly_mean

            adaniports  asianpaints    axisbank       cipla         tcs
Date
2008-01-01  697.245902  1122.013443  890.177869  202.536066  851.202459
2008-04-01  664.475833  1194.307167  790.570000  211.437500  881.163333
2008-07-01  574.631452  1154.575484  724.050806  221.054032  803.908065
2008-10-01  438.815873  1006.242540  611.223016  193.703968  626.427778

In [ ]:
fig = px.bar(df_stocks_quarterly_mean, x=df_stocks_quarterly_mean.index, y="asianpaints")
fig.update_layout(title="Quarterly average stock price",xaxis_title="Quarter")
fig.show()

In [ ]:
fig = px.bar(df_stocks_quarterly_mean, x=df_stocks_quarterly_mean.index, y=["asianpaints","tcs"],barmode='group')
fig.update_layout(title="Quarterly average stock price",xaxis_title="Quarter")
fig.show()

## Recompute the Quarterly Mean

In [ ]:
df_stocks_quarterly_mean = df_stocks.groupby(pd.PeriodIndex(df_stocks['Date'], freq="Q")).mean()

In [ ]:
df_stocks_quarterly_mean

        adaniports  asianpaints    axisbank       cipla         tcs
Date
2008Q1  697.245902  1122.013443  890.177869  202.536066  851.202459
2008Q2  664.475833  1194.307167  790.570000  211.437500  881.163333
2008Q3  574.631452  1154.575484  724.050806  221.054032  803.908065
2008Q4  438.815873  1006.242540  611.223016  193.703968  626.427778

In [ ]:
index_list = list(df_stocks_quarterly_mean.index)

new_index_list = []

for index in index_list:
  new_index = str(index)
  new_index_list.append(new_index)

df_stocks_quarterly_mean.index = new_index_list

In [ ]:
df_stocks_quarterly_mean

        adaniports  asianpaints    axisbank       cipla         tcs
2008Q1  697.245902  1122.013443  890.177869  202.536066  851.202459
2008Q2  664.475833  1194.307167  790.570000  211.437500  881.163333
2008Q3  574.631452  1154.575484  724.050806  221.054032  803.908065
2008Q4  438.815873  1006.242540  611.223016  193.703968  626.427778

In [ ]:
fig = px.bar(df_stocks_quarterly_mean, x=df_stocks_quarterly_mean.index, y="asianpaints")
fig.update_layout(title="Quarterly average stock price",xaxis_title="Quarter")
fig.show()

**DIY:**

Do a bar plot of the coefficient of quartile deviation for each month. Do it for one stock on a bar graph, and then for two stocks on the same bar graph.

**DIY:**

Do a bar plot of the coefficient of variation for each month. Do it for one stock on a bar graph, and then for two stocks on the same bar graph.

# Scatter plots and Line Plots

In [ ]:
df_stocks

         Date  adaniports  asianpaints  axisbank   cipla      tcs
0    01/01/08     1296.85      1123.19    972.55  211.10  1054.55
1    02/01/08     1307.45      1135.45   1034.65  218.85  1050.00
2    03/01/08     1275.80      1133.90   1035.85  216.35  1011.05
3    04/01/08     1240.35      1150.08   1054.90  213.65  1005.20
4    07/01/08     1227.25      1182.62   1090.15  212.65   975.60
..        ...         ...          ...       ...     ...      ...
241  24/12/08      312.80       868.23    490.75  181.05   478.15
242  26/12/08      305.45       868.44    482.80  181.95   471.65
243  29/12/08      315.75       867.77    494.95  184.00   476.80
244  30/12/08      319.70       873.45    510.25  183.90   482.55
245  31/12/08      325.30       883.53    504.70  186.60   477.90

[246 rows x 6 columns]

In [ ]:
fig = px.bar(df_stocks_monthly_mean, x=df_stocks_monthly_mean.index, y="asianpaints",error_y = df_stocks_monthly_std["asianpaints"])
fig.update_layout(title="Monthly average stock price",xaxis_title="Month")
fig.show()

In [ ]:
fig = px.line(df_stocks_monthly_mean, x=df_stocks_monthly_mean.index, y="asianpaints", title='Stock Mean Price per Month')
fig.show()

In [ ]:
fig = go.Figure()
fig.add_trace(
    go.Bar(
      name='Asian Paints',
      x=df_stocks_monthly_mean.index, y=df_stocks_monthly_mean["asianpaints"],
      error_y=dict(type='data',array = np.array(df_stocks_monthly_std["asianpaints"]))))

fig.add_trace(
    go.Scatter(
      name='Asian Paints',
      x=df_stocks_monthly_mean.index, y=df_stocks_monthly_mean["asianpaints"]))


fig.update_layout(barmode='group',xaxis_title="Month")
fig.show()

In [ ]:
# Plot monthly values for TCS and Asian Paints using Line Chart

fig = go.Figure()

fig.add_trace(
    go.Scatter(
      name='TCS',
      x=df_stocks_monthly_mean.index, y=df_stocks_monthly_mean["tcs"]))

fig.add_trace(
    go.Scatter(
      name='Asian Paints',
      x=df_stocks_monthly_mean.index, y=df_stocks_monthly_mean["asianpaints"]))

fig.update_layout(barmode='group',xaxis_title="Month")
fig.show()

**DIY:**

Use for-loop to plot monthly values for all the stocks on a Line Chart

# Daily Price

In [ ]:
fig = px.line(df_stocks, x="Date", y="asianpaints", title='Stock Price per Day')
# fig = px.scatter(df_stocks, x="Date", y="asianpaints", title='Stock Price per Day')
fig.show()

## **DIY:**

Plot the **daily** price of Asian Paints and TCS on the same graph.

## **DIY:**

Plot the **daily** price of all stocks on the same graph

## **DIY:**

At the beginning of the year, you had 400 stocks of Asian Paints, 700 stocks of TCS and 1900 stocks of Cipla. Plot the total market value of your stocks on a daily and monthly basis.

In [ ]:
df_stocks

         Date  adaniports  asianpaints  axisbank   cipla      tcs
0    01/01/08     1296.85      1123.19    972.55  211.10  1054.55
1    02/01/08     1307.45      1135.45   1034.65  218.85  1050.00
2    03/01/08     1275.80      1133.90   1035.85  216.35  1011.05
3    04/01/08     1240.35      1150.08   1054.90  213.65  1005.20
4    07/01/08     1227.25      1182.62   1090.15  212.65   975.60
..        ...         ...          ...       ...     ...      ...
241  24/12/08      312.80       868.23    490.75  181.05   478.15
242  26/12/08      305.45       868.44    482.80  181.95   471.65
243  29/12/08      315.75       867.77    494.95  184.00   476.80
244  30/12/08      319.70       873.45    510.25  183.90   482.55
245  31/12/08      325.30       883.53    504.70  186.60   477.90

[246 rows x 6 columns]

In [ ]:
market_value_list = []

for i in range(len(df_stocks)):

  price_asianpaints = df_stocks.loc[i]["asianpaints"]

  price_tcs = df_stocks.loc[i]["tcs"]

  price_cipla = df_stocks.loc[i]["cipla"]

  # 400 stocks of Asian Paints, 700 stocks of TCS and 1900 stocks of Cipla
  market_value = 400*price_asianpaints + 700*price_tcs + 1900*price_cipla

  market_value_list.append(market_value)

df_market_value = pd.DataFrame()
df_market_value["Personal"] = market_value_list
df_market_value["Date"] = list(df_stocks["Date"])

In [ ]:
df_market_value

      Personal      Date
0    1588551.0  01/01/08
1    1604995.0  02/01/08
2    1572360.0  03/01/08
3    1569607.0  04/01/08
4    1560003.0  07/01/08
..         ...       ...
241  1025992.0  24/12/08
242  1023236.0  26/12/08
243  1030468.0  29/12/08
244  1036575.0  30/12/08
245  1042482.0  31/12/08

[246 rows x 2 columns]

In [ ]:
fig = px.line(df_market_value, x="Date", y="Personal", title='Personal Stock Market Value per Day')
# fig = px.scatter(df_stocks, x="Date", y="asianpaints", title='Stock Price per Day')
fig.show()

# Heatmap (Optional)

In [ ]:
x = df_stocks["Date"]

y = list(df_stocks.columns)
y.remove("Date")

z = []
for col in df_stocks.columns:
  if col != "Date":
    z.append(df_stocks[col])

In [ ]:
trace = go.Heatmap(
   x = x,
   y = y,
   z = z,
   type = 'heatmap',
   colorscale = 'Viridis'
)
data = [trace]
fig = go.Figure(data = data)
fig.show()

# Pie Charts

In [ ]:
stock_names = ["asianpaints","tcs","cipla"]
stock_value_start = [df_stocks.iloc[0][stock] for stock in stock_names]

In [ ]:
stock_names

['asianpaints', 'tcs', 'cipla']

In [ ]:
stock_value_start

[1123.19, 1054.55, 211.1]

In [ ]:
fig = px.pie(names=stock_names, values=stock_value_start)
fig.show()

In [ ]:
stock_value_end = [df_stocks.iloc[-1][stock] for stock in stock_names]

fig = px.pie(names=stock_names, values=stock_value_end)
fig.show()

# Subplots

In [ ]:
fig = make_subplots(rows=1, cols=2,specs=[[{"type": "domain"}, {"type": "domain"}]], subplot_titles=("Start Valuation","End Valuation"))

fig.add_trace(
    go.Pie(labels=stock_names, values=stock_value_start, domain=dict(x=[0, 0.5])),
    row=1, col=1)

fig.add_trace(
    go.Pie(labels=stock_names, values=stock_value_end, domain=dict(x=[0.5, 1.0])),
    row=1, col=2)

fig.update_layout(height=600, width=800, title_text="Stock Valuations")
fig.show()

## **Think:**

Is it a good idea to use pie charts instead of bar charts?